### ISSUE TITLE
hiredis线程安全问题

### ISSUE THREAD

**Issue by Miyamoto-Konatsu** [Tiannia/Simple-ChatServer#1]
你好，我正在学习你的这个项目，我想问下，你在chatservice里的_redis成员如何保证线程安全？

**Comment by Tiannia** [comment]
你好，查看了一下，chatservice的_redis没有考虑到线程安全问题。谢谢提醒~

**Comment by Miyamoto-Konatsu** [comment]
> 

好的，谢谢你的项目

**Comment by Miyamoto-Konatsu** [comment]
> 你好，查看了一下，chatservice的_redis没有考虑到线程安全问题。谢谢提醒~

好的，谢谢你的项目，学到很多
